// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnRoY8jObZoMADCOzcKl9gtndNIAiIoWw',
    appId: '1:991606466546:web:1acf9e0328e47bfb65ad6b',
    messagingSenderId: '991606466546',
    projectId: 'hiokdev-flutter-app',
    authDomain: 'hiokdev-flutter-app.firebaseapp.com',
    storageBucket: 'hiokdev-flutter-app.appspot.com',
    measurementId: 'G-XG9QBFFQ89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByK_TZa--EwZp3hBaGurKp8UZxvFZSxv4',
    appId: '1:991606466546:android:9f5b731a4d7a7cd565ad6b',
    messagingSenderId: '991606466546',
    projectId: 'hiokdev-flutter-app',
    storageBucket: 'hiokdev-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1y-y3TzNqZcT4S--Kq4XR7fF8DYSSqEU',
    appId: '1:991606466546:ios:6b9c11568d40592265ad6b',
    messagingSenderId: '991606466546',
    projectId: 'hiokdev-flutter-app',
    storageBucket: 'hiokdev-flutter-app.appspot.com',
    iosBundleId: 'br.com.hioktec.flutter.firebase.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1y-y3TzNqZcT4S--Kq4XR7fF8DYSSqEU',
    appId: '1:991606466546:ios:d26d8e9dc3c86d4065ad6b',
    messagingSenderId: '991606466546',
    projectId: 'hiokdev-flutter-app',
    storageBucket: 'hiokdev-flutter-app.appspot.com',
    iosBundleId: 'br.com.hioktec.flutter.firebase.firebaseApp.RunnerTests',
  );
}
